### ISSUE TITLE
TypeError: get_item() got an unexpected keyword argument 'silent'

### ISSUE THREAD

**Issue by benjamin-pike** [john-corcoran/internetarchive-downloader#5]
I've received the following error whilst attempting to download an archive.

`python3 ia_downloader.py download ARCHIVE_ID output`
```
Traceback (most recent call last):
  File "ia_downloader.py", line 1849, in main
    download(
  File "ia_downloader.py", line 1293, in download
    download_pool.map(file_download, download_queue, chunksize=1)
  File "/Users/benjaminpike/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/benjaminpike/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/Users/benjaminpike/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/benjaminpike/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "ia_downloader.py", line 594, in file_download
    internetarchive.download(
  File "/Users/benjaminpike/opt/anaconda3/lib/python3.8/site-packages/internetarchive/api.py", line 378, in download
    item = get_item(identifier, **get_item_kwargs)
TypeError: get_item() got an unexpected keyword argument 'silent'
```

**Comment by john-corcoran** [comment]
Thanks for the note, looks like a breaking change was made in the latest version of the internetarchive Python library (v3.0.0).

This error should now be fixed in release v1.0.5: https://github.com/john-corcoran/internetarchive-downloader/releases/tag/v1.0.5
